module.exports = {
  BAD_REQUEST: 'BAD_REQUEST',

  UNAUTHORIZED: 'UNAUTHORIZED',

  FORBIDDEN: 'FORBIDDEN',

  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  CONFLICT: 'CONFLICT',

  ERROR: 'INTERNAL_SERVER_ERROR',
};
